import { ImageOff, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import type { PreviewImage } from "../app/page";
import { assetUrl, type JobRead } from "../lib/api";
import { resultTypeLabel, riskLabel } from "../lib/presentation";
import { ImageCompareSlider } from "./ImageCompareSlider";

type ImageSize = {
  width: number;
  height: number;
};

export function ResultCompare({ job, preview }: { job: JobRead | null; preview: PreviewImage | null }) {
  const [selectedResultId, setSelectedResultId] = useState<string | null>(null);
  const [imageSizes, setImageSizes] = useState<Record<string, ImageSize>>({});

  const selectedResult = useMemo(() => {
    if (!job?.results.length) {
      return null;
    }
    return job.results.find((result) => result.id === selectedResultId) ?? job.results[0];
  }, [job, selectedResultId]);

  const originalUrl = preview?.url ?? (job?.original_url ? assetUrl(job.original_url) : "");
  const selectedResultUrl = selectedResult ? assetUrl(selectedResult.url) : "";

  function saveImageSize(key: string, image: HTMLImageElement) {
    setImageSizes((current) => ({
      ...current,
      [key]: {
        width: image.naturalWidth,
        height: image.naturalHeight
      }
    }));
  }

  async function copyResultId(resultId: string) {
    if (!navigator.clipboard) {
      window.prompt("复制结果 ID", resultId);
      return;
    }
    try {
      await navigator.clipboard.writeText(resultId);
    } catch {
      window.prompt("复制结果 ID", resultId);
    }
  }

  return (
    <section className="result-panel">
      <div className="panel-heading">
        <div>
          <h2 className="section-title">原图与候选结果</h2>
          <p className="subtle">完成后可在这里对比原图、保真版、写实版和锐化版。</p>
        </div>
        <span className="panel-icon">
          <Sparkles size={18} />
        </span>
      </div>
      {originalUrl ? (
        <article className="original-preview">
          {/* Local object URL is used for demo preview only. */}
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src={originalUrl} alt="原图预览" onLoad={(event) => saveImageSize("original", event.currentTarget)} />
          <div>
            <strong>{preview ? "原图预览" : "历史任务原图"}</strong>
            <p className="subtle">
              {preview ? preview.name : "刷新页面后已从任务详情恢复原图"}
              {imageSizes.original ? ` · ${imageSizes.original.width} x ${imageSizes.original.height}` : ""}
            </p>
          </div>
        </article>
      ) : null}
      {!job || job.results.length === 0 ? (
        <div className="empty-state visual-empty">
          <ImageOff size={26} />
          <strong>等待生成结果</strong>
          <span>任务完成后会显示候选图、质量分、风险等级和下载入口。</span>
        </div>
      ) : null}
      {job?.results.length ? (
        <div className="result-tabs">
          {job.results.map((result) => (
            <button
              key={result.id}
              type="button"
              className={`segment ${selectedResult?.id === result.id ? "active" : ""}`}
              onClick={() => setSelectedResultId(result.id)}
            >
              {resultTypeLabel(result.type)}
            </button>
          ))}
        </div>
      ) : null}
      {originalUrl && selectedResultUrl && selectedResult ? (
        <div className="compare-block">
          <ImageCompareSlider
            beforeLabel="原图"
            beforeUrl={originalUrl}
            afterLabel={resultTypeLabel(selectedResult.type)}
            afterUrl={selectedResultUrl}
          />
          <div className="compare-meta">
            <span>倍率：{job?.scale}x</span>
            <span>结果尺寸：{imageSizes[selectedResult.id] ? `${imageSizes[selectedResult.id].width} x ${imageSizes[selectedResult.id].height}` : "加载后显示"}</span>
            <span>模型：{selectedResult.model_name} / {selectedResult.model_version}</span>
          </div>
        </div>
      ) : null}
      <div className="result-grid">
        {job?.results.map((result) => (
          <article className="result-card" key={result.id}>
            {/* Result URLs are generated by the API storage service; Next image optimization is intentionally bypassed in MVP. */}
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={assetUrl(result.url || result.thumbnail_url)}
              alt={`${result.type} result`}
              onLoad={(event) => saveImageSize(result.id, event.currentTarget)}
            />
            <div className="result-meta">
              <div className="result-heading">
                <strong>{resultTypeLabel(result.type)}</strong>
                <span className={`risk-badge risk-${result.risk_level}`}>{riskLabel(result.risk_level)}</span>
              </div>
              <div>模型：{result.model_name} / {result.model_version}</div>
              <div>尺寸：{imageSizes[result.id] ? `${imageSizes[result.id].width} x ${imageSizes[result.id].height}` : "加载后显示"}</div>
              <div>质量分：{result.quality_score}</div>
              <code>{result.id}</code>
              <div className="result-actions">
                <a href={assetUrl(result.url)} target="_blank" rel="noreferrer">打开结果</a>
                <a href={assetUrl(result.url)} download>下载结果</a>
                <button type="button" className="link-button" onClick={() => copyResultId(result.id)}>复制 ID</button>
              </div>
            </div>
          </article>
        ))}
      </div>
    </section>
  );
}
